main: thirtyvirus.template.BattleChristmas
version: 1.0
name: BattleChristmas
api-version: 1.13

commands:
  bc:
    description: Main command for BattleChristmas. Use /template help for more info
permissions:
  template.user:
    description: Allows player to use the plugin's user features
    default: true
  template.admin:
    description: Allows player to use the plugin's admin features
    default: op